FROM messiazmonteiro/odoo20-core:20.0
USER root
# COPY requirements.txt /tmp/requirements.txt
# RUN pip3 install --no-cache-dir --break-system-packages -r /tmp/requirements.txt
# COPY --chown=odoo:odoo ./addons /mnt/extra-addons
USER odoo
